/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frontend;
import backend.Musico;
import backend.GestaoSistema;
import backend.Album;
import backend.Sessao;
import java.util.ArrayList;

/**
 *
 * @author marco
 */
public class albunsMusicoDialog extends javax.swing.JDialog {

    /**
     * Creates new form albunsMusicoDialog
     */
    GestaoSistema sistema;
    Musico musico;
    
    
    public albunsMusicoDialog(java.awt.Frame parent, boolean modal, Musico musico, GestaoSistema lista) {
        super(parent, modal);
        this.sistema = lista;
        this.musico = musico;
        initComponents();
        preencherTabela();
    }
    
    public void preencherTabela(){
        ArrayList<Album> albuns_musico = musico.getAlbunsAssociados(sistema.getAlbuns());
        ArrayList<Sessao> sessoes_musico = musico.getSessoesAgendadas(albuns_musico);
        for(int i = 0; i < sessoes_musico.size(); i++) {
            if(sessoes_musico.get(i) != null) {
                this.tbSessoesMusico.setValueAt(sessoes_musico.get(i).getAlbum().getTitulo(), i, 0);
                this.tbSessoesMusico.setValueAt(sessoes_musico.get(i).getDataI(), i, 1);
                if(sessoes_musico.get(i).isConclusao()){
                    this.tbSessoesMusico.setValueAt("Concluido",i,2);
                }
                else{
                    this.tbSessoesMusico.setValueAt("Em andamento",i,2);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbSessoesMusico = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbSessoesMusico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Album", "Data agendada", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbSessoesMusico);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 649, 208));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 328, 75, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pexels-francesco-ungaro-281260.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSessoesMusico;
    // End of variables declaration//GEN-END:variables
}
