/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frontend;
import backend.Album;
import backend.Sessao;
import backend.GestaoSistema;
import javax.swing.*;

/**
 *
 * @author marco
 */
public class albumSessoesDialog extends javax.swing.JDialog {

    /**
     * Creates new form albumSessoesDialog
     */
    public Album album;
    GestaoSistema sistema;
    
    public albumSessoesDialog(java.awt.Frame parent, boolean modal, Album album, GestaoSistema lista) {
        super(parent, modal);
        this.album = album;
        this.sistema= lista;
        initComponents();
        receberDados();
        this.setLocationRelativeTo(null);
    }
    
    public void receberDados(){
        album_titulo.setText(album.getTitulo());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        album_titulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Atribuir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        data_inicio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        album_titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        album_titulo.setText("album_titulo");
        getContentPane().add(album_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 23, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Gravacao do album");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 23, -1, -1));

        Atribuir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Atribuir.setText("Agendar sessao");
        Atribuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtribuirActionPerformed(evt);
            }
        });
        getContentPane().add(Atribuir, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 177, 165, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Introduza uma data (no formato dd-mm hh:mm) para agendar uma sessao de gravacao a este album:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 75, -1, -1));
        getContentPane().add(data_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 101, 122, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pexels-francesco-ungaro-281260.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtribuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtribuirActionPerformed
        // TODO add your handling code here:
        if(data_inicio.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Data esta vazia!");
        }
        else{
            Sessao novasessao = new Sessao(album,data_inicio.getText());
            sistema.adicionarSessao(novasessao);
            album.adicionarSessoes(novasessao);
            JOptionPane.showMessageDialog(this, "A sessao foi agendada com sucesso!");
            this.dispose();
        }
    }//GEN-LAST:event_AtribuirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atribuir;
    private javax.swing.JLabel album_titulo;
    private javax.swing.JTextField data_inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
