/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import javax.swing.*;

import projetofinal.GestaoSistema;
import projetofinal.Utilizador;
import projetofinal.Musico;
import projetofinal.Musica;
import java.util.ArrayList;

/**
 *
 * @author marco
 */
public class criarMusica extends javax.swing.JFrame {

    GestaoSistema sistema;
    private DefaultListModel<String> modelMusicosSelecionados;

    /**
     * Creates new form criarMusica
     */
    public criarMusica(GestaoSistema lista) {
        initComponents();
        this.sistema = lista;
        this.preencherTabela();
        modelMusicosSelecionados = new DefaultListModel<>();
        lstMusicosSelecionados.setModel(modelMusicosSelecionados);

    }

    public void preencherTabela() {
        ArrayList<Utilizador> utilizadores = this.sistema.getUtilizadores();
        int row = 0;
        for (int i = 0; i < utilizadores.size(); i++) {
            if (utilizadores.get(i) != null) {
                if (utilizadores.get(i) instanceof Musico) {
                    Musico m = (Musico) utilizadores.get(i);
                    this.tbMusicos.setValueAt(m.getNome(), row, 0);
                    row++;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbMusicos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        titulo_musica = new javax.swing.JTextField();
        duracao_musica = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adicionarMusico = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        removerMusico = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMusicosSelecionados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbMusicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome dos Musicos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbMusicos);

        jLabel2.setText("Adicione os musicos selecionando uma linha na tabela e pressionando o botao adicionar.");

        jLabel3.setText("Duracao (segundos)");

        jLabel4.setText("Titulo");

        adicionarMusico.setText("Adicionar musico");
        adicionarMusico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarMusicoActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");

        jButton3.setText("Criar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        removerMusico.setText("Remover musico");
        removerMusico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerMusicoActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstMusicosSelecionados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(duracao_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adicionarMusico)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(removerMusico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel2)))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_musica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duracao_musica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adicionarMusico)
                        .addGap(18, 18, 18)
                        .addComponent(removerMusico)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarMusicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarMusicoActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbMusicos.getSelectedRow();
        if (selectedRow >= 0) {
            String nomeMusico = (String) tbMusicos.getValueAt(selectedRow, 0);
            if (!modelMusicosSelecionados.contains(nomeMusico)) {
                modelMusicosSelecionados.addElement(nomeMusico);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um músico na tabela primeiro.");
        }
    }//GEN-LAST:event_adicionarMusicoActionPerformed

    private void removerMusicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerMusicoActionPerformed
        // TODO add your handling code here:
        int selectedIndex = lstMusicosSelecionados.getSelectedIndex();
        if (selectedIndex >= 0) {
            modelMusicosSelecionados.remove(selectedIndex);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um músico na lista para remover.");
        }
    }//GEN-LAST:event_removerMusicoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String titulo = titulo_musica.getText().trim();
        String duracaoStr = duracao_musica.getText().trim();

        //dar erro se nao preencher algum campo
        if (titulo.isEmpty() || duracaoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios.");
            return;
        }

        try {
            int duracao = Integer.parseInt(duracaoStr);
            if (duracao <= 0) {
                JOptionPane.showMessageDialog(this, "A duração deve ser maior que zero.");
                return;
            }

            //receber musicos selecionados
            DefaultListModel<String> model = (DefaultListModel<String>) lstMusicosSelecionados.getModel();
            if (modelMusicosSelecionados.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Selecione pelo menos um músico.");
                return;
            }

            //criar objeto musica
            Musica novaMusica = new Musica(titulo, duracao);
            //novaMusica.musicos = new ArrayList<>();

            //adicionar musicos selecionados
            ArrayList<Utilizador> utilizadores = sistema.getUtilizadores();
            for (int i = 0; i < model.size(); i++) {
                String nomeMusico = model.getElementAt(i);
                for (Utilizador u : utilizadores) {
                    if (u instanceof Musico && ((Musico) u).getNome().equals(nomeMusico)) {
                        novaMusica.musicos.add((Musico) u);
                        break;
                    }
                }
            }

            sistema.adicionarMusica(novaMusica);

            JOptionPane.showMessageDialog(this, "Música criada com sucesso!");
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Duração deve ser um número válido.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarMusico;
    private javax.swing.JTextField duracao_musica;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstMusicosSelecionados;
    private javax.swing.JButton removerMusico;
    private javax.swing.JTable tbMusicos;
    private javax.swing.JTextField titulo_musica;
    // End of variables declaration//GEN-END:variables
}
