/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import backend.Musico;

/**
 *
 * @author marco
 */
public class dadosMusico extends javax.swing.JFrame {

    public Musico musico;
    
    /**
     * Creates new form dadosMusico
     */
    public dadosMusico(Musico musico) {
        initComponents();
        this.musico = musico;
        receberDados();
        this.setLocationRelativeTo(null);
    }

    public void receberDados(){
        user_musico.setText(musico.getUserName());
        name.setText(musico.getNome());
        dataNasc.setText(musico.getDataNascimento());
        Dmorada.setText(musico.getMorada());
        ident.setText(musico.getNumeroidentificacao());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        user_musico = new javax.swing.JLabel();
        dataNasc = new javax.swing.JLabel();
        Dmorada = new javax.swing.JLabel();
        ident = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setText("Editar");

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_musico.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        user_musico.setText("username");
        getContentPane().add(user_musico, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 28, 139, -1));

        dataNasc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dataNasc.setText("dataNasc");
        getContentPane().add(dataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 124, 281, -1));

        Dmorada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Dmorada.setText("Dmorada");
        getContentPane().add(Dmorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 155, 281, -1));

        ident.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ident.setText("ident");
        getContentPane().add(ident, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 186, 281, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Morada");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 155, 78, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Data de Nascimento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, 78, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("CNI");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 186, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Dados de");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 28, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name.setText("name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 93, 281, -1));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 247, 75, -1));

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 247, 75, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pexels-francesco-ungaro-281260.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Fechar a tela
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        editarMusicoDialog dialog = new editarMusicoDialog(this, true);
        
        dialog.setDados(name.getText(),dataNasc.getText(),Dmorada.getText(),ident.getText());
        
        dialog.setVisible(true);
        
        if (dialog.isConfirmado()) {
            musico.editarDados(dialog.getCNome(),dialog.getCData(),dialog.getCMorada(),dialog.getCCni());
            
           receberDados();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dmorada;
    private javax.swing.JLabel dataNasc;
    private javax.swing.JLabel ident;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel user_musico;
    // End of variables declaration//GEN-END:variables
}
