/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import projetofinal.Produtor;
        
/**
 *
 * @author marco
 */
public class dadosProdutor extends javax.swing.JFrame {
    
    public Produtor produtor;

    /**
     * Creates new form dadosProdutor
     */
    public dadosProdutor(Produtor produtor) {
        initComponents();
        this.produtor = produtor;
        receberDados();
        
    }
    
    public void receberDados(){
        user_produtor.setText(produtor.getUserName());
        nome_produtor.setText(produtor.getNomep());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_produtor = new javax.swing.JLabel();
        nome_produtor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        user_produtor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user_produtor.setText("jLabel1");

        nome_produtor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nome_produtor.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user_produtor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome_produtor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(user_produtor)
                .addGap(34, 34, 34)
                .addComponent(nome_produtor)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nome_produtor;
    private javax.swing.JLabel user_produtor;
    // End of variables declaration//GEN-END:variables
}
