/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import java.util.ArrayList;
import backend.Produtor;
import backend.Album;
import backend.GestaoSistema;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class edicaoAlbum extends javax.swing.JFrame {

    /**
     * Creates new form edicaoAlbum
     */
    public Produtor produtor;
    GestaoSistema sistema;
    
    public edicaoAlbum(Produtor produtor, GestaoSistema lista) {
        initComponents();
        this.produtor = produtor;
        this.sistema = lista;
        this.preencherTabela();
        this.setLocationRelativeTo(null);
        
    }
    
    public void preencherTabela() {
        ArrayList<Album> albuns = this.produtor.getAlbunsProduzidos();
        for(int i = 0; i < albuns.size(); i++) {
            if(albuns.get(i) != null) {
                this.tbAlbunsProd.setValueAt(albuns.get(i).getTitulo(), i, 0);
                this.tbAlbunsProd.setValueAt(albuns.get(i).getTipo(), i, 1);
                //datainicio
                if(albuns.get(i).getDataEdicao() != null){
                    this.tbAlbunsProd.setValueAt(albuns.get(i).getDataEdicao(), i, 2);
                }
                else{
                    this.tbAlbunsProd.setValueAt("Sem data de inicio", i, 2);
                }
                //datafinal
                if(albuns.get(i).getDataFinal() != null){
                    this.tbAlbunsProd.setValueAt(albuns.get(i).getDataFinal(), i, 3);
                }
                else{
                    this.tbAlbunsProd.setValueAt("Sem Data Final", i, 3);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbAlbunsProd = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbAlbunsProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, "", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Tipo", "Inicio", "Final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbAlbunsProd);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, 650, 149));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Lista de albuns a produzir");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 20, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Iniciar edicao do album");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 224, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 312, 75, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Ver/Editar sessoes do album");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 224, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pexels-francesco-ungaro-281260.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selecao = tbAlbunsProd.getSelectedRow();
        if(selecao<0){
            JOptionPane.showMessageDialog(this, "Nao foi selecionado um album!");
        }
        //colocar a data de inicio
        ArrayList<Album> albuns = this.produtor.getAlbunsProduzidos();
        for(int i = 0; i < albuns.size(); i++) {
            albuns.get(selecao).setDataEdicao();
        }
        //abrir o dialog para criar sessoes do album
        albumSessoesDialog asd = new albumSessoesDialog(this,true,albuns.get(selecao),sistema);
        asd.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selecao = tbAlbunsProd.getSelectedRow();
        if(selecao<0){
            JOptionPane.showMessageDialog(this, "Nao foi selecionado um album!");
        }
        //selecao do album
        ArrayList<Album> albuns = this.produtor.getAlbunsProduzidos();
        //abrir dialog para ver as sessoes e conclui-las
        verSessoesDialog vsd = new verSessoesDialog(this,true,albuns.get(selecao), sistema);
        vsd.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAlbunsProd;
    // End of variables declaration//GEN-END:variables
}
