/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frontend;

/**
 *
 * @author marco
 */
public class editarMusicoDialog extends javax.swing.JDialog {

    private boolean confirmado = false;
    
    /**
     * Creates new form editarMusico
     */
    public editarMusicoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void setDados(String nome, String dataNasc, String morada, String cni) {
        campo_nome.setText(nome);
        campo_data.setText(dataNasc);
        campo_morada.setText(morada);
        campo_cni.setText(cni);
    }

    public boolean isConfirmado() {
        return confirmado;
    }

    public String getCNome() {
        return campo_nome.getText();
    }
    
    public String getCData() {
        return campo_data.getText();
    }
    
    public String getCMorada() {
        return campo_morada.getText();
    }
    
    public String getCCni() {
        return campo_cni.getText();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        campo_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campo_data = new javax.swing.JTextField();
        campo_morada = new javax.swing.JTextField();
        campo_cni = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 248, 115, -1));

        campo_nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(campo_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 70, 252, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 73, 78, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Data de Nascimento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Morada");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 147, 78, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("CNI");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 184, -1, -1));

        campo_data.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(campo_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 107, 252, -1));

        campo_morada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(campo_morada, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 144, 252, -1));

        campo_cni.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campo_cni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_cniActionPerformed(evt);
            }
        });
        getContentPane().add(campo_cni, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 181, 252, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 248, 115, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Editar os seus dados");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 16, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pexels-francesco-ungaro-281260.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        confirmado = true;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void campo_cniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_cniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_cniActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo_cni;
    private javax.swing.JTextField campo_data;
    private javax.swing.JTextField campo_morada;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
