/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import java.util.ArrayList;
import backend.GestaoSistema;
import backend.Album;
import backend.Sessao;

/**
 *
 * @author marco
 */
public class estatisticaTotal extends javax.swing.JFrame {

    /**
     * Creates new form estatisticaTotal
     */
    
    GestaoSistema sistema;
    
    public estatisticaTotal(GestaoSistema lista) {
        initComponents();
        this.sistema = lista;
        calcularTotal();
        calcularMedia();
        this.setLocationRelativeTo(null);
    }
    
    
    public void calcularTotal(){
        ArrayList<Album> albuns = this.sistema.getAlbuns();
        int total_albuns = 0;
        int total_albuns_concluidos=0;
        for(Album a: albuns){
            if(!a.getEstado())
                total_albuns++;
            else if(a.getEstado()){
                total_albuns_concluidos++;
            }
        }
        total_album_edicao.setText(""+total_albuns);
        albuns_concluidos.setText(""+total_albuns_concluidos);
    }
    
    public void calcularMedia(){
        ArrayList<Album> albuns = this.sistema.getAlbuns();
        int total_albuns = albuns.size();
        double soma = 0;
        for(Album a: albuns){
            soma += a.calcularProgressoTotal();
        }
        
        double media = soma/total_albuns;
                
        media_sessoes.setText(""+media);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        media_sessoes = new javax.swing.JLabel();
        albuns_concluidos = new javax.swing.JLabel();
        total_album_edicao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Total de albuns em edicao");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 75, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Media de sessoes concluidas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 139, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Total de albuns concluidos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 203, -1, -1));

        media_sessoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        media_sessoes.setText("media_sessoes");
        getContentPane().add(media_sessoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 139, -1, -1));

        albuns_concluidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        albuns_concluidos.setText("albuns_concluidos");
        getContentPane().add(albuns_concluidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 203, -1, -1));

        total_album_edicao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        total_album_edicao.setText("total_album_edicao");
        getContentPane().add(total_album_edicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 75, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Estatisticas gerais");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 24, -1, -1));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 261, 75, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pexels-francesco-ungaro-281260.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel albuns_concluidos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel media_sessoes;
    private javax.swing.JLabel total_album_edicao;
    // End of variables declaration//GEN-END:variables
}
