/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import java.util.ArrayList;
import backend.GestaoSistema;
import backend.Album;
import backend.Sessao;

/**
 *
 * @author marco
 */
public class estatisticaTotal extends javax.swing.JFrame {

    /**
     * Creates new form estatisticaTotal
     */
    
    GestaoSistema sistema;
    
    public estatisticaTotal(GestaoSistema lista) {
        initComponents();
        this.sistema = lista;
        calcularTotal();
        calcularMedia();
    }
    
    
    public void calcularTotal(){
        ArrayList<Album> albuns = this.sistema.getAlbuns();
        int total_albuns = 0;
        int total_albuns_concluidos=0;
        for(Album a: albuns){
            if(!a.getEstado())
                total_albuns++;
            else if(a.getEstado()){
                total_albuns_concluidos++;
            }
        }
        total_album_edicao.setText(""+total_albuns);
        albuns_concluidos.setText(""+total_albuns_concluidos);
    }
    
    public void calcularMedia(){
        ArrayList<Album> albuns = this.sistema.getAlbuns();
        int total_albuns = albuns.size();
        double soma = 0;
        for(Album a: albuns){
            soma += a.calcularProgressoTotal();
        }
        
        double media = soma/total_albuns;
                
        media_sessoes.setText(""+media);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        media_sessoes = new javax.swing.JLabel();
        albuns_concluidos = new javax.swing.JLabel();
        total_album_edicao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Total de albuns em edicao");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Media de sessoes concluidas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Total de albuns concluidos");

        media_sessoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        media_sessoes.setText("media_sessoes");

        albuns_concluidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        albuns_concluidos.setText("albuns_concluidos");

        total_album_edicao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        total_album_edicao.setText("total_album_edicao");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Estatisticas gerais");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total_album_edicao)
                    .addComponent(media_sessoes)
                    .addComponent(albuns_concluidos))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(total_album_edicao)
                        .addGap(39, 39, 39)
                        .addComponent(media_sessoes)
                        .addGap(39, 39, 39)
                        .addComponent(albuns_concluidos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel albuns_concluidos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel media_sessoes;
    private javax.swing.JLabel total_album_edicao;
    // End of variables declaration//GEN-END:variables
}
