/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import javax.swing.*;

import backend.Instrumento;
import backend.GestaoSistema;
import backend.Requisicao;
import java.util.ArrayList;
import backend.Album;
import backend.Sessao;
import backend.Musico;

/**
 *
 * @author marco
 */
public class fazerRequisicao extends javax.swing.JFrame {

    /**
     * Creates new form fazerRequisicao
     */
    GestaoSistema sistema;
    Musico musico;
    private DefaultListModel<String> modelInstrumentosSelecionados;
    
    public fazerRequisicao(GestaoSistema lista, Musico musico) {
        initComponents();
        this.sistema = lista;
        this.musico = musico;
        this.preencherTabela();
        modelInstrumentosSelecionados = new DefaultListModel<>();
        lstInstrumentosSelecionados.setModel(modelInstrumentosSelecionados);
        this.setLocationRelativeTo(null);
    }
    
    public void preencherTabela() {
        //preencher tabela de instrumentos
        ArrayList<Instrumento> instrumentos = sistema.getInstrumentos();
        for(int i = 0; i < instrumentos.size(); i++) {
            if(instrumentos.get(i) != null) {
                this.tbInstrumento.setValueAt(instrumentos.get(i).getNome(), i, 0);
                this.tbInstrumento.setValueAt(instrumentos.get(i).getTipo(), i, 1);
                if (instrumentos.get(i).getEstado() == true){
                    this.tbInstrumento.setValueAt("Disponivel", i, 2);
                }
                else{
                    this.tbInstrumento.setValueAt("Indisponivel", i, 2);
                }
            }
        }
        //preencher tabela de sessoes
        ArrayList<Album> albuns_musico = musico.getAlbunsAssociados(sistema.getAlbuns());
        ArrayList<Sessao> sessoes_musico = musico.getSessoesAgendadas(albuns_musico);
        for(int i = 0; i < sessoes_musico.size(); i++) {
            if(sessoes_musico.get(i) != null) {
                this.tbSessoesMusico.setValueAt(sessoes_musico.get(i).getAlbum().getTitulo(), i, 0);
                this.tbSessoesMusico.setValueAt(sessoes_musico.get(i).getDataI(), i, 1);
                if(sessoes_musico.get(i).isConclusao()){
                    this.tbSessoesMusico.setValueAt("Concluido",i,2);
                }
                else{
                    this.tbSessoesMusico.setValueAt("Em andamento",i,2);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbInstrumento = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSessoesMusico = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstInstrumentosSelecionados = new javax.swing.JList<>();
        adicionar = new javax.swing.JButton();
        remover = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbInstrumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Tipo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbInstrumento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 404, 190));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 555, -1, -1));

        jButton2.setText("Requirir instrumento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 555, -1, -1));

        tbSessoesMusico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Titulo", "Data agendada", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbSessoesMusico);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 266, 696, 248));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Lista de sessoes agendadas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Lista de instrumentos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 6, -1, -1));

        jScrollPane3.setViewportView(lstInstrumentosSelecionados);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 32, 125, 190));

        adicionar.setText("Adicionar");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });
        getContentPane().add(adicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 32, -1, -1));

        remover.setText("Remover");
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });
        getContentPane().add(remover, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 83, 80, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pexels-francesco-ungaro-281260.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> model = (DefaultListModel<String>) lstInstrumentosSelecionados.getModel();
        ArrayList<Album> albuns_musico = musico.getAlbunsAssociados(sistema.getAlbuns());
        ArrayList<Sessao> sessoes_musico = musico.getSessoesAgendadas(albuns_musico);
        
        int selecao = tbSessoesMusico.getSelectedRow();
        
        if(sessoes_musico.get(selecao)!=null || musico != null){
            Requisicao novaReq = new Requisicao(sessoes_musico.get(selecao),musico);
   
            ArrayList<Instrumento> instrumentos = sistema.getInstrumentos();
            for (int i = 0; i < model.size(); i++) {
                String nomeInstrumento = model.getElementAt(i);
                for (Instrumento ins : instrumentos) {
                    if (ins.getNome().equals(nomeInstrumento)) {
                        novaReq.adicionarInstrumento(ins);
                        break;
                    }
                }
            }
            if(novaReq.getInstrumento().isEmpty()){
                JOptionPane.showMessageDialog(this, "A requesicao nao tem instrumentos validos");
            } else{
                sistema.adicionarRequisicao(novaReq);
                JOptionPane.showMessageDialog(this, "A requisicao foi adicionada no sistema");
            }
        } else{
            JOptionPane.showMessageDialog(this, "A sessao ou o musico sao invalidos");
        }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbInstrumento.getSelectedRow();
        if (selectedRow >= 0) {
            String nomeInstrumento = (String) tbInstrumento.getValueAt(selectedRow, 0);
            if (!modelInstrumentosSelecionados.contains(nomeInstrumento)) {
                modelInstrumentosSelecionados.addElement(nomeInstrumento);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um músico na tabela primeiro.");
        }
    }//GEN-LAST:event_adicionarActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        // TODO add your handling code here:
        int selectedIndex = lstInstrumentosSelecionados.getSelectedIndex();
        if (selectedIndex >= 0) {
            modelInstrumentosSelecionados.remove(selectedIndex);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um músico na lista para remover.");
        }
    }//GEN-LAST:event_removerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstInstrumentosSelecionados;
    private javax.swing.JButton remover;
    private javax.swing.JTable tbInstrumento;
    private javax.swing.JTable tbSessoesMusico;
    // End of variables declaration//GEN-END:variables
}
