/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import projetofinal.GestaoSistema;
import projetofinal.Requisicao;
import java.util.ArrayList;
/**
 *
 * @author marco
 */
public class listaRequisicoes extends javax.swing.JFrame {

    /**
     * Creates new form listaRequisicoes
     */
    GestaoSistema sistema;
    public listaRequisicoes(GestaoSistema lista) {
        this.sistema=lista;
        initComponents();
        preencherTabela();
    }
    
    public void preencherTabela(){
        ArrayList<Requisicao> requisicoes = this.sistema.getRequisicoes();
        for(int i = 0; i < requisicoes.size(); i++) {
            if(requisicoes.get(i) != null) {
                this.tbRequisicoes.setValueAt(requisicoes.get(i).getSessao().getAlbum().getTitulo(), i, 0);
                this.tbRequisicoes.setValueAt(requisicoes.get(i).getSessao().getDataI(), i, 1);
                this.tbRequisicoes.setValueAt(requisicoes.get(i).getMusico().getNome(), i, 2);
                this.tbRequisicoes.setValueAt(requisicoes.get(i).getData(), i, 3);
                this.tbRequisicoes.setValueAt(requisicoes.get(i).getEstado(), i, 4);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbRequisicoes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        permitir = new javax.swing.JButton();
        recusar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbRequisicoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Album", "Sessao", "Musico", "Data", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbRequisicoes);

        jLabel1.setText("Lista de requisicoes de cada sessao do album correspondente");

        permitir.setText("Permitir");
        permitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permitirActionPerformed(evt);
            }
        });

        recusar.setText("Recusar");
        recusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recusarActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(permitir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(recusar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 205, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(permitir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recusar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recusarActionPerformed
        // TODO add your handling code here:
        int selecao = tbRequisicoes.getSelectedRow();
        ArrayList<Requisicao> requisicoes = this.sistema.getRequisicoes();
        //alterar o estado apenas se for pendente
        if(requisicoes.get(selecao).getEstado().equals("Pendente")){
        requisicoes.get(selecao).recusarReq();
        }
        System.out.println("Requisicao foi recusada");
    }//GEN-LAST:event_recusarActionPerformed

    private void permitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permitirActionPerformed
        // TODO add your handling code here:
        int selecao = tbRequisicoes.getSelectedRow();
        ArrayList<Requisicao> requisicoes = this.sistema.getRequisicoes();
        //alterar o estado apenas se for pendente
        if(requisicoes.get(selecao).getEstado().equals("Pendente")){
            requisicoes.get(selecao).aceitarReq();
        }
        System.out.println("Requisicao foi atribuida");
    }//GEN-LAST:event_permitirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton permitir;
    private javax.swing.JButton recusar;
    private javax.swing.JTable tbRequisicoes;
    // End of variables declaration//GEN-END:variables
}
