/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import backend.GestaoSistema;
import backend.Requisicao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author marco
 */
public class listaRequisicoes extends javax.swing.JFrame {

    /**
     * Creates new form listaRequisicoes
     */
    GestaoSistema sistema;
    public listaRequisicoes(GestaoSistema lista) {
        this.sistema=lista;
        initComponents();
        preencherTabela();
        this.setLocationRelativeTo(null);
    }
    
    public void preencherTabela(){
        ArrayList<Requisicao> requisicoes = this.sistema.getRequisicoes();
        for(int i = 0; i < requisicoes.size(); i++) {
            if(requisicoes.get(i) != null) {
                this.tbRequisicoes.setValueAt(requisicoes.get(i).getSessao().getAlbum().getTitulo(), i, 0);
                this.tbRequisicoes.setValueAt(requisicoes.get(i).getSessao().getDataI(), i, 1);
                this.tbRequisicoes.setValueAt(requisicoes.get(i).getMusico().getNome(), i, 2);
                this.tbRequisicoes.setValueAt(requisicoes.get(i).getData(), i, 3);
                this.tbRequisicoes.setValueAt(requisicoes.get(i).getEstado(), i, 4);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbRequisicoes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        permitir = new javax.swing.JButton();
        recusar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbRequisicoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Album", "Sessao", "Musico", "Data", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbRequisicoes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 708, 241));

        jLabel1.setText("Lista de requisicoes de cada sessao do album correspondente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 6, -1, -1));

        permitir.setText("Permitir");
        permitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permitirActionPerformed(evt);
            }
        });
        getContentPane().add(permitir, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 293, 75, 26));

        recusar.setText("Recusar");
        recusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recusarActionPerformed(evt);
            }
        });
        getContentPane().add(recusar, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 293, 75, 26));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 343, 75, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pexels-francesco-ungaro-281260.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recusarActionPerformed
        // TODO add your handling code here:
        int selecao = tbRequisicoes.getSelectedRow();
        if(selecao<0){
            JOptionPane.showMessageDialog(this, "Nao foi selecionada uma requisicao!");
        } else{
            ArrayList<Requisicao> requisicoes = this.sistema.getRequisicoes();
            //alterar o estado apenas se for pendente
            if(requisicoes.get(selecao).getEstado().equals("Pendente")){
            requisicoes.get(selecao).recusarReq();
            }
            JOptionPane.showMessageDialog(this, "Requisicao foi recusada");
        }
    }//GEN-LAST:event_recusarActionPerformed

    private void permitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permitirActionPerformed
        // TODO add your handling code here:
        int selecao = tbRequisicoes.getSelectedRow();
        if(selecao<0){
            JOptionPane.showMessageDialog(this, "Nao foi selecionada uma requisicao!");
        } else{
            ArrayList<Requisicao> requisicoes = this.sistema.getRequisicoes();
            //alterar o estado apenas se for pendente
            if(requisicoes.get(selecao).getEstado().equals("Pendente")){
                requisicoes.get(selecao).aceitarReq();
            }
            JOptionPane.showMessageDialog(this, "Requisicao foi atribuida");
        }
    }//GEN-LAST:event_permitirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton permitir;
    private javax.swing.JButton recusar;
    private javax.swing.JTable tbRequisicoes;
    // End of variables declaration//GEN-END:variables
}
