/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.util.ArrayList;
import backend.GestaoSistema;
import backend.Musico;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class registoMusico extends javax.swing.JFrame {

    GestaoSistema sistema;
    public String user;
    public String pass;
    
    /**
     * Creates new form registoMusico
     */
    public registoMusico(GestaoSistema lista, String user, String pass) {
        initComponents();
        this.sistema = lista;
        this.user = user;
        this.pass = pass;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        morada_musico = new javax.swing.JTextField();
        nome_musico = new javax.swing.JTextField();
        cni_musico = new javax.swing.JTextField();
        dataNasc_musico = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Morada");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 186, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("CNI");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 251, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Registo de novo Musico");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Nome");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Data de nascimento");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 121, -1, -1));

        morada_musico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morada_musicoActionPerformed(evt);
            }
        });
        getContentPane().add(morada_musico, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 217, 339, -1));

        nome_musico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_musicoActionPerformed(evt);
            }
        });
        getContentPane().add(nome_musico, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 87, 339, -1));

        cni_musico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cni_musicoActionPerformed(evt);
            }
        });
        getContentPane().add(cni_musico, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 282, 339, -1));

        dataNasc_musico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNasc_musicoActionPerformed(evt);
            }
        });
        getContentPane().add(dataNasc_musico, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 152, 339, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Registar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 336, 93, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 336, 93, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pexels-francesco-ungaro-281260.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void morada_musicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morada_musicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_morada_musicoActionPerformed

    private void nome_musicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_musicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_musicoActionPerformed

    private void cni_musicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cni_musicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cni_musicoActionPerformed

    private void dataNasc_musicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNasc_musicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNasc_musicoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nomemusic = nome_musico.getText();
        String dataNa = dataNasc_musico.getText();
        String morada = morada_musico.getText();
        String cni = cni_musico.getText();
        
        Musico m = new Musico(user,pass,nomemusic,morada,dataNa,cni);
        sistema.adicionarUtilizador(m);
        JOptionPane.showMessageDialog(this, "Musico criado com sucesso!");
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cni_musico;
    private javax.swing.JTextField dataNasc_musico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField morada_musico;
    private javax.swing.JTextField nome_musico;
    // End of variables declaration//GEN-END:variables
}
