/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.GestaoSistema;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class registoUtilizador extends javax.swing.JFrame {

    /**
     * Creates new form registoUtilizador
     */
    
    GestaoSistema sistema;
    
    public registoUtilizador(GestaoSistema lista) {
        initComponents();
        this.sistema = lista;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tipo_reg = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        username_reg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        password_reg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 79, 127, -1));

        tipo_reg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tipo_reg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Musico", "Produtor" }));
        getContentPane().add(tipo_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 282, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tipo de utilizador");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 251, -1, -1));

        username_reg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_regActionPerformed(evt);
            }
        });
        getContentPane().add(username_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 116, 304, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Registar um novo utilizador");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 20, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Registar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 331, 87, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 331, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 165, 127, -1));

        password_reg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(password_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 202, 304, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pexels-francesco-ungaro-281260.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void username_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_regActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user = username_reg.getText();
        String pass = password_reg.getText();
        String tipo = tipo_reg.getSelectedItem().toString();
        if(user.isEmpty() || pass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Alguma informacao esta vazia!");
        } else {
            if (tipo.equals("Produtor")){
                registoProdutor rp = new registoProdutor(sistema, user, pass);
                rp.setVisible(true);
                this.dispose();
            }
            else{
                registoMusico rm = new registoMusico(sistema, user, pass);
                rm.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField password_reg;
    private javax.swing.JComboBox<String> tipo_reg;
    private javax.swing.JTextField username_reg;
    // End of variables declaration//GEN-END:variables
}
