/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import javax.swing.*;

import backend.GestaoSistema;
import backend.Musica;
import backend.Album;
import backend.Utilizador;
import backend.Produtor;
import java.util.ArrayList;

/**
 *
 * @author marco
 */
public class registoAlbum extends javax.swing.JFrame {

    /**
     * Creates new form registoAlbum
     */
    
    GestaoSistema sistema;
    private DefaultListModel<String> modelMusicasSelecionadas;

    
    public registoAlbum(GestaoSistema lista) {
        initComponents();
        this.sistema = lista;
        this.preencherTabela();
        modelMusicasSelecionadas = new DefaultListModel<>();
        lstMusicasSelecionadas.setModel(modelMusicasSelecionadas);
    }
    
    public void preencherTabela() {
        //Preencher a tabela de musicas
        ArrayList<Musica> musicas = this.sistema.getMusicas();
        for (int i = 0; i < musicas.size(); i++) {
            if (musicas.get(i) != null) {
                int minuto = (musicas.get(i).getDuracao())/60;
                int segundos = (musicas.get(i).getDuracao()%60);
                this.tbMusicas.setValueAt(musicas.get(i).getTitulo(), i, 0);
                this.tbMusicas.setValueAt(""+minuto+":"+""+segundos, i, 1);
            }
        }
        //Preencher a tabela de produtores
        ArrayList<Utilizador> utilizadores = this.sistema.getUtilizadores();
        int row = 0;
        for (int i = 0; i < utilizadores.size(); i++) {
            if (utilizadores.get(i) != null) {
                if (utilizadores.get(i) instanceof Produtor) {
                    Produtor prod = (Produtor) utilizadores.get(i);
                    this.tbProdutores.setValueAt(prod, row, 0);
                    this.tbProdutores.setValueAt(prod.getNomep(), row, 1);
                    row++;
                }
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_album = new javax.swing.JTextField();
        tipo_album = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMusicasSelecionadas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMusicas = new javax.swing.JTable();
        adicionarMusicas = new javax.swing.JButton();
        removerMusicas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProdutores = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(titulo_album, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 16, 109, -1));
        getContentPane().add(tipo_album, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 16, 109, -1));

        jLabel1.setText("Titulo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 19, 37, -1));

        jLabel2.setText("Tipo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 19, 37, -1));

        jScrollPane1.setViewportView(lstMusicasSelecionadas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 119, 187, 166));

        tbMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Titulo", "Duracao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbMusicas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, 374, 213));

        adicionarMusicas.setText("Adicionar");
        adicionarMusicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarMusicasActionPerformed(evt);
            }
        });
        getContentPane().add(adicionarMusicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 78, -1, -1));

        removerMusicas.setText("Remover");
        removerMusicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerMusicasActionPerformed(evt);
            }
        });
        getContentPane().add(removerMusicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 78, 80, -1));

        jLabel3.setText("Musicas selecionadas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 44, -1, -1));

        jButton3.setText("Criar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 462, 75, -1));

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 462, -1, -1));

        tbProdutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome do Produtor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbProdutores);
        if (tbProdutores.getColumnModel().getColumnCount() > 0) {
            tbProdutores.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 325, 374, 102));

        jLabel4.setText("Selecione o produtor que produz o album");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 291, -1, -1));

        jLabel5.setText("Selecione as musicas que pertencem ao album");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 44, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pexels-francesco-ungaro-281260.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarMusicasActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbMusicas.getSelectedRow();
        if (selectedRow >= 0) {
            String nomeMusico = (String) tbMusicas.getValueAt(selectedRow, 0);
            if (!modelMusicasSelecionadas.contains(nomeMusico)) {
                modelMusicasSelecionadas.addElement(nomeMusico);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um músico na tabela primeiro.");
        }
    }//GEN-LAST:event_adicionarMusicasActionPerformed

    private void removerMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerMusicasActionPerformed
        // TODO add your handling code here:
        int selectedIndex = lstMusicasSelecionadas.getSelectedIndex();
        if (selectedIndex >= 0) {
            modelMusicasSelecionadas.remove(selectedIndex);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um músico na lista para remover.");
        }
    }//GEN-LAST:event_removerMusicasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String titulo = titulo_album.getText().trim();
        String tipo = tipo_album.getText().trim();

        //dar erro se nao preencher algum campo
        if (titulo.isEmpty() || tipo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios.");
            return;
        }

        //receber musicas selecionados
        DefaultListModel<String> model = (DefaultListModel<String>) lstMusicasSelecionadas.getModel();
        if (modelMusicasSelecionadas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione pelo menos uma musica.");
            return;
        }
        
        //escolher o produtor responsavel pelo album
        int selecao = tbProdutores.getSelectedRow();
        Produtor produtor = (Produtor) tbProdutores.getValueAt(selecao, 0);
       
        //criar objeto album
        Album novoAlbum = new Album(titulo, tipo, produtor);

        //adicionar musicas selecionadas
        ArrayList<Musica> musicas = sistema.getMusicas();
        for (int i = 0; i < model.size(); i++) {
            String tituloMusica = model.getElementAt(i);
            for (Musica m : musicas) {
                if (m.getTitulo().equals(tituloMusica)) {
                    novoAlbum.musicas.add(m);
                    break;
                }
            }
        }
        
        //adicionar album no sistema e na lista do produtor
        sistema.adicionarAlbum(novoAlbum);
        produtor.adicionarAlbum(novoAlbum);

        JOptionPane.showMessageDialog(this, "Album criado com sucesso!");
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarMusicas;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstMusicasSelecionadas;
    private javax.swing.JButton removerMusicas;
    private javax.swing.JTable tbMusicas;
    private javax.swing.JTable tbProdutores;
    private javax.swing.JTextField tipo_album;
    private javax.swing.JTextField titulo_album;
    // End of variables declaration//GEN-END:variables
}
