/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frontend;
import backend.Sessao;
import backend.Album;
import java.util.ArrayList;

/**
 *
 * @author marco
 */
public class verSessoesDialog extends javax.swing.JDialog {

    public Album album;
    
    /**
     * Creates new form verSessoesDialog
     */
    public verSessoesDialog(java.awt.Frame parent, boolean modal, Album album) {
        super(parent, modal);
        this.album = album;
        initComponents();
        this.preencherTabela();
        
    }
    
    public void preencherTabela() {
        ArrayList<Sessao> sessoes = this.album.getSessoes();
        for(int i = 0; i < sessoes.size(); i++) {
            if(sessoes.get(i) != null) {
                //estado
                if(sessoes.get(i).isConclusao()){
                    tbSessoes.setValueAt("Concluida",i,0);
                }
                else{ 
                    tbSessoes.setValueAt("Nao concluida",i,0); 
                }
                //data agendada
                tbSessoes.setValueAt(sessoes.get(i).getDataI(),i,1);
                //data final
                if(sessoes.get(i).getDataf()!=null){
                    tbSessoes.setValueAt(sessoes.get(i).getDataf(),i,2);
                }
                else{
                    tbSessoes.setValueAt("Sem data",i,2);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbSessoes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbSessoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Estado", "Data agendada", "Data de conclusao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbSessoes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 19, 540, 220));

        jButton1.setText("Concluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 251, 75, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Selecione uma sessao na tabela que deseja concluir");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 251, -1, -1));

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 294, 75, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pexels-francesco-ungaro-281260.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selecao = tbSessoes.getSelectedRow();
        ArrayList<Sessao> sessoes = this.album.getSessoes();
        if(selecao != -1){
            sessoes.get(selecao).Concluir();
            System.out.println("A sessao foi concluida");
        }
        else{
            System.out.println("Selecione uma sessao na tabela primeiro!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        ArrayList<Sessao> sessoes = this.album.getSessoes();
        //verificar se todas as sessoes foram concluidas
        boolean todasConcluidas = true;
        for(Sessao sessao: sessoes){
            if(!sessao.isConclusao()){
                todasConcluidas = false;
                break;
            }
        }
        //se forem concluidas atribuir a data final ao album
        if(this.album.getDataFinal() == null){
            if(todasConcluidas){
                System.out.println("Todas as sessoes foram concluidas");
                this.album.setDataFinal();
                this.album.setEstado(true);
            }else{ 
                System.out.println("Ainda ha sessoes em andamento"); 
            }
        }
        else{
            System.out.println("A gravacao do album foi concluida");
        }
        //voltar e fechar a janela
        this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSessoes;
    // End of variables declaration//GEN-END:variables
}
